version: "3"

services:
    recommender-service:
        build:
            context: .
            dockerfile: ./recommender.dockerfile
        restart: always
        deploy:
            mode: replicated
            replicas: 1
